"""Immutable synthetic regression staging for a constrained local candidate."""
from dataclasses import dataclass
import hashlib
from pathlib import Path
import subprocess
from tempfile import TemporaryDirectory
import json

from src.services.local_code_candidate_service import TARGETS, validate_candidate
from src.services.windows_sandbox_test_runner import WindowsSandboxTestRunner

TESTS = (
    "tests/test_filename_policy_service.py",
    "tests/test_review_reason_summary_service.py",
    "tests/test_reference_filename_builder.py",
    "tests/test_production_filename_assembly_service.py",
    "tests/test_intake_filename_architecture.py",
    "tests/test_smartsheet_review_row_mapping.py",
)


@dataclass(frozen=True)
class LocalCandidateTestResult:
    passed: bool
    category: str
    candidate_digest: str = ""
    cleanup_proven: bool = False
    exit_code: int | None = None


class LocalCandidateTestService:
    def __init__(self, *, runner=None):
        from src.services.local_correction_memory_service import LocalCorrectionStore
        self.runner=runner or WindowsSandboxTestRunner(owner_store=LocalCorrectionStore())

    def verify(self, *, root, candidate, applied=False):
        root=Path(root).resolve()
        if candidate.path not in TARGETS.values():
            raise ValueError("local_candidate_scope_invalid")
        validate_candidate(candidate.before,candidate.after,candidate.changed_function)
        expected=candidate.after if applied else candidate.before
        if (root/candidate.path).read_text(encoding="utf-8-sig") != expected:
            return LocalCandidateTestResult(False,"local_candidate_baseline_changed")
        # Only explicit tracked code/test content, never git metadata or ignored data.
        result=subprocess.run(["git","ls-files","-z","--","src","tests"],
            cwd=root,capture_output=True,timeout=30,check=False)
        if result.returncode:
            return LocalCandidateTestResult(False,"local_test_manifest_unavailable")
        paths=result.stdout.decode("utf-8").split("\0")
        with TemporaryDirectory(prefix="lthhc-code-tests-") as folder:
            stage=Path(folder)
            inputs=stage/"input"; inputs.mkdir()
            source=inputs/"source"; source.mkdir()
            for relative in paths:
                if not relative:
                    continue
                rel=Path(relative)
                if relative not in TESTS and not (relative.startswith("src/") and rel.suffix in {".py",".json"}):
                    continue
                original=root/rel
                if not original.is_file() or not original.resolve().is_relative_to(root) or original.is_symlink():
                    return LocalCandidateTestResult(False,"local_test_manifest_invalid")
                target=source/rel
                target.parent.mkdir(parents=True,exist_ok=True)
                target.write_bytes(original.read_bytes())
            if any(not (source/name).is_file() for name in TESTS):
                return LocalCandidateTestResult(False,"local_test_manifest_incomplete")
            (source/candidate.path).write_text(candidate.after,encoding="utf-8")
            # Generated by trusted broker, never by the model. Each discovered
            # fixture must actually execute; simply importing a script is not a test.
            harness=(
                "import ast, pathlib, runpy, sys\n"
                "root=pathlib.Path(__file__).parent/'source'\n"
                "sys.path.insert(0,str(root))\n"
                "sys.path.append(str(pathlib.Path(sys.executable).parent/'Lib/site-packages'))\n"
                "total=0\n"
                "for index,relative in enumerate("+repr(TESTS)+"):\n"
                " ordinal=-1\n"
                " try:\n"
                "  path=root/relative\n"
                "  expected=sum(isinstance(n,ast.FunctionDef) and n.name.startswith('test_') for n in ast.parse(path.read_text(encoding='utf-8-sig')).body)\n"
                "  namespace=runpy.run_path(str(path))\n"
                "  tests=[v for k,v in namespace.items() if k.startswith('test_') and callable(v)]\n"
                "  assert expected>0 and len(tests)==expected\n"
                "  for ordinal,test in enumerate(tests): test(); total+=1\n"
                " except ModuleNotFoundError:\n"
                "  sys.exit(200+index)\n"
                " except BaseException:\n"
                "  sys.exit(1000+index*100+ordinal if ordinal>=0 else 100+index)\n"
                "assert total>0\n"
            )
            (inputs/"run_tests.py").write_text(harness,encoding="utf-8")
            self.runner.stage_python(stage/"runtime", dependencies=("smartsheet-python-sdk","python-dotenv"))
            outcome=self.runner.run(input_dir=inputs,runtime_dir=stage/"runtime")
            return LocalCandidateTestResult(
                outcome.success,outcome.category,
                hashlib.sha256(candidate.after.encode("utf-8")).hexdigest(),
                outcome.cleanup_proven,
                outcome.exit_code,
            )
