from src.business_rules.rule_factory import RuleFactory
from src.models.document import Document


class RuleService:
    """
    Executes business rules for processed documents.
    """

    def execute(self, document: Document) -> list:
        """
        Execute the appropriate business rule for a document.

        Args:
            document: The processed document.

        Returns:
            A list of actions generated by the business rule.
        """

        rule = RuleFactory.create(document.document_type)

        return rule.execute(document)