from abc import ABC, abstractmethod

from src.models.document import Document


class Rule(ABC):
    """
    Base class for all business rule plugins.

    Every business rule is responsible for processing a single
    document type and returning a list of actions to perform.
    """

    # The document type this rule handles.
    # Derived classes should override this value.
    document_type: str = ""

    @abstractmethod
    def execute(self, document: Document) -> list:
        """
        Execute business rules for the supplied document.

        Args:
            document: Document produced by the DocumentProcessor.

        Returns:
            A list of actions generated by the rule.
        """
        pass